"""Mint `zoo_keeper/core/pixel_type_glyphs.py` from Pixelcoat's typeface.

    python tools/mint_pixel_type.py [--pixelcoat <pixelcoat repo>] [--check]

THE FACTORY OWNS ONE TYPEFACE: Pixel Operator, CC0, vendored by Pixelcoat at
`assets/fonts/pixel_operator/` and set by `pixelcoat/core/signage.py` for
every shop sign. Zoo lettering that is a TEXTURE (0.87.0: a vending machine's
backlit panel) is set in the same face, so a machine's brand and the shop
sign over the door are one typeface.

WHY A TABLE AND NOT THE TTF. Zoo builds inside Blender, whose Python carries
numpy and no PIL, and a TrueType rasteriser is not something to write twice.
Pixel Operator is drawn on a 16 px grid: set at 16 px every glyph is a pure
bitmap (0 or 255, nothing between), and at 32 px it is exactly the 16 px
bitmap doubled -- both measured with PIL before this was written, on
"IGGLES TEARS", 0 of 64,000 pixels different. The face has no kerning: a
string rendered by PIL equals its glyphs composed at their advances (on
"Tastes Like the Boulevard at 2 AM.", every pixel). So the 16 px bitmaps and
advances ARE the typeface at every multiple of its grid, and a table of them
loses nothing.

`--check` re-renders from the TTF and exits 1 if the table differs, which is
also what `tests/test_vending_machine.py` does when Pixelcoat is present.
Run with PYTHONDONTWRITEBYTECODE=1: this imports Pixelcoat read-only.
"""
from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ZOO = os.path.dirname(HERE)
OUT = os.path.join(ZOO, "zoo_keeper", "core", "pixel_type_glyphs.py")
#: Printable ASCII and the cent sign a 1997 price display needs.
CHARSET = "".join(chr(c) for c in range(32, 127)) + "¢"
PX = 16


def default_pixelcoat():
    env = os.environ.get("PIXELCOAT_DIR")
    if env:
        return env
    return os.path.join(os.path.dirname(ZOO), "pixelcoat")


def render_table(pixelcoat_dir, weight="bold"):
    sys.dont_write_bytecode = True
    sys.path.insert(0, pixelcoat_dir)
    from pixelcoat.core import signage  # noqa: E402
    from PIL import Image, ImageDraw, ImageFont  # noqa: E402
    path = os.path.join(signage.FONT_DIR, signage.FONT_FILES[weight])
    face = ImageFont.truetype(path, PX)
    top, bottom = 0, 0
    for ch in CHARSET:
        b = face.getbbox(ch, anchor="ls")
        top, bottom = min(top, b[1]), max(bottom, b[3])
    glyphs = {}
    for ch in CHARSET:
        adv = face.getlength(ch)
        if adv != int(adv):
            raise SystemExit(f"{ch!r}: advance {adv} is not whole pixels")
        adv = int(adv)
        w = max(adv, face.getbbox(ch, anchor="ls")[2])
        img = Image.new("L", (w, bottom - top), 0)
        ImageDraw.Draw(img).text((0, -top), ch, fill=255, font=face, anchor="ls")
        px = img.load()
        rows = []
        for y in range(bottom - top):
            vals = [px[x, y] for x in range(w)]
            if any(v not in (0, 255) for v in vals):
                raise SystemExit(f"{ch!r}: antialiased at {PX} px -- not a grid face")
            rows.append("".join("#" if v else "." for v in vals))
        glyphs[ch] = (adv, tuple(rows))
    return {"ascent": -top, "descent": bottom, "px": PX,
            "font": os.path.basename(path), "glyphs": glyphs}


def emit(table):
    lines = [
        '"""Pixel Operator Bold at 16 px, as bitmaps. GENERATED by',
        "tools/mint_pixel_type.py from Pixelcoat's vendored TTF -- do not edit;",
        "re-mint. Pixel Operator by Jayvee Enaguas, CC0 1.0 (see Pixelcoat's",
        'assets/fonts/pixel_operator/README.md)."""',
        "",
        f"FONT = {table['font']!r}",
        f"PX = {table['px']}",
        "#: rows above the baseline (row ``ASCENT`` is the first below it)",
        f"ASCENT = {table['ascent']}",
        f"DESCENT = {table['descent']}",
        "#: char -> (advance px, rows top to bottom, '#' ink)",
        "GLYPHS = {",
    ]
    for ch, (adv, rows) in table["glyphs"].items():
        lines.append(f"    {ch!r}: ({adv}, (")
        for r in rows:
            lines.append(f"        {r!r},")
        lines.append("    )),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pixelcoat", default=default_pixelcoat())
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = emit(render_table(a.pixelcoat))
    if a.check:
        have = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        print("pixel_type_glyphs.py", "matches" if have == text else "DIFFERS",
              "the TTF at", a.pixelcoat)
        return 0 if have == text else 1
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote", OUT, len(text), "bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
